### ISSUE TITLE
ldapscripts and Debian stretch

### ISSUE THREAD

**Issue by plegrand1** [martymac/ldapscripts#10]
Hello, iv' got a problem since i upgrade my server to Debian stretch.

```
Debian GNU/Linux 9 (stretch)
Paquet : slapd                                          
Version : 2.4.44+dfsg-5
Paquet : ldapscripts                                    
Version : 2.0.7-2
```

No problem to create user with ldapadduser.
But each time i remove a user with ldapdeleteuser, i've got these error message : 

```
ldap_modify: Server is unwilling to perform (53)
additional info: modify upon the root DSE not supported
```

Do you know what could be the problem ?
Thanks for your help.

**Comment by muzzol** [comment]
without more details is hard to tell, but it seems a problem about ldadmodify being unable to identify the root base. can try to you execute?:
`
ldapsearch -x -b '' -s base
`

**Comment by plegrand1** [comment]
Hello, thanks for your answer
Tell me what kind of details you need.

**From the ldap server itself :** 
`ldapsearch -x -b 'dc=annuaire,dc=fr' -s base`

```
# extended LDIF
#
# LDAPv3
# base <dc=annuaire,dc=fr> with scope baseObject
# filter: (objectclass=*)
# requesting: ALL
#

# annuaire.fr
dn: dc=annuaire,dc=fr
objectClass: top
objectClass: dcObject
objectClass: organization
o: annuaire
dc: annuaire

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1

```

**From the server Samba**
`ldapsearch -x -h 192.168.151.247 -b 'dc=annuaire,dc=fr' -s base`

```
# extended LDIF
#
# LDAPv3
# base <dc=annuaire,dc=fr> with scope baseObject
# filter: (objectclass=*)
# requesting: ALL
#

# annuaire.fr
dn: dc=annuaire,dc=fr
objectClass: top
objectClass: dcObject
objectClass: organization
o: annuaire
dc: annuaire

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1


```

**Comment by plegrand1** [comment]
sept. 04 16:03:16 samba4 ldapscripts: ldapadduser(root): /usr/sbin/ldapadduser toto gim.1
  -> Successfully added user toto to LDAP
  -> Successfully set password for user toto
  -> Successfully created home directory for user toto

sept. 04 16:04:07 samba4 ldapscripts: ldapdeleteuser(root): /usr/sbin/ldapdeleteuser toto
  -> Deleting user from secondary group: 
ldap_modify: Server is unwilling to perform (53)
	additional info: modify upon the root DSE not supported
  -> Successfully deleted user uid=toto,ou=Users,ou=Samba,dc=annuaire,dc=fr from LDAP


**Logs in the ldap server**

```
Sep  5 09:54:48 tamtam slapd[1588]: conn=1037 fd=33 ACCEPT from IP=192.168.151.237:53314 (IP=0.0.0.0:389)
Sep  5 09:54:48 tamtam slapd[1588]: conn=1037 op=0 BIND dn="cn=root,dc=annuaire,dc=fr" method=128
Sep  5 09:54:48 tamtam slapd[1588]: conn=1037 op=0 BIND dn="cn=root,dc=annuaire,dc=fr" mech=SIMPLE ssf=0
Sep  5 09:54:48 tamtam slapd[1588]: conn=1037 op=0 RESULT tag=97 err=0 text=
Sep  5 09:54:48 tamtam slapd[1588]: conn=1037 op=1 MOD dn=""
Sep  5 09:54:48 tamtam slapd[1588]: conn=1037 op=1 MOD attr=memberUid
Sep  5 09:54:48 tamtam slapd[1588]: conn=1037 op=1 do_modify: root dse!
Sep  5 09:54:48 tamtam slapd[1588]: conn=1037 op=1 RESULT tag=103 err=53 text=modify upon the root DSE not supported
```

**Comment by martymac** [comment]
Hi,

(sorry for lagging)

It seems that ldapdeleteuser is trying to modify an empty entry (empty variable "", interpreted as root DSE) returned by the '_findentries' function.

That should not be the case.

Can you tell me what GCLASS you are using in ldapscripts.conf ?

Can you also provide LDIF of user toto (once created) as well as his secondary group(s), if any ?

**Comment by plegrand1** [comment]
Hello,
No problem for lagging

I use ldapscripts since a long time ago.
I dont know if you remember, but i made some changes inside ldapadduser and ldapdeleteuser
to modify home directory according to primary group

**ldapadduser**

```
# User GID = second argument
_GROUP="$2"
_GID=$(_grouptogid "$2")
[ -z "$_GID" ] && end_die "Cannot resolve group $2 to gid : not found"
```

```
# Compute homedir
#_HOMEDIR=$(echo "$UHOMES" | sed "s|%u|$_USER|g")
#_HOMEDIR=`echo "$UHOMES" | sed -e "s|%u|$_USER|g"`
_HOMEDIR=`echo "$UHOMES" | sed -e "s|%u|$_USER|g" -e "s|%g|$_GROUP|g"`
#UHOMES modifié dans ldapscript.conf
```

**ldapdeleteuser**

```
# Delete entry
# Delete home directory
 rm -fr `ldapsearch -x -H "$SERVER" -b "$SUFFIX" "(&(uid=$1)(objectClass=posixAccount))" homeDirectory | awk '(/^homeDirectory/){print $2}'`
```


GCLASS="posixGroup"   # Leave "posixGroup" here if not sure !

**ldapadduser toto gim.1**

```
Successfully added user toto to LDAP
Successfully set password for user toto
Successfully created home directory for user toto
```
**ldapsearch -x -h 192.168.151.247 -b 'dc=annuaire,dc=fr' '(uid=toto)'**

```
# extended LDIF
#
# LDAPv3
# base <dc=annuaire,dc=fr> with scope subtree
# filter: (uid=toto)
# requesting: ALL
#

# toto, Users, Samba, annuaire.fr
dn: uid=toto,ou=Users,ou=Samba,dc=annuaire,dc=fr
objectClass: account
objectClass: posixAccount
cn: toto
uid: toto
uidNumber: 32947
gidNumber: 10007
homeDirectory: /home/users/gim.1/toto
loginShell: /bin/false
gecos: toto
description: User account

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1
```

**Comment by martymac** [comment]
OK, thanks. Is toto member of any secondary group ?

If you look at the code of ldapdeleteuser, I think that "$_ENTRY" becomes empty (line 56).

Can you try to display its value as well as the value of "$_ENTRIES" (line 53) ?

**Comment by plegrand1** [comment]
toto is not member of any secondary group 

**ldapadduser toto gim.1**
```
Successfully added user toto to LDAP
Successfully set password for user toto
Successfully created home directory for user toto
```
I put `echo $_ENTRY` just after `[ -z "$_ENTRY" ] && end_die "User $1 not found in LDAP"`
then 
**ldapdeleteuser toto**
```
uid=toto,ou=Users,ou=Samba,dc=annuaire,dc=fr
Deleting user from secondary group: 
Successfully deleted user uid=toto,ou=Users,ou=Samba,dc=annuaire,dc=fr from LDAP
```

I cant see how to display $_ENTRIES


But if i understand you make :
`_ldapdelete "$_UDN" || end_die "Error deleting user $_UDN from LDAP"`
And after that
`# Finally, delete this user from all his secondary groups`
But the user doesn't exist anymore no ?

**Comment by muzzol** [comment]
you can debug adding some lines like this
`
echo "DEBUG: _ENTRY [$_ENTRY] _ENTRIES [$_ENTRIES]"
`

where martymac told you

**Comment by plegrand1** [comment]
then i put just after this line : 
`_findentries "$GSUFFIX,$SUFFIX" "(&(objectClass=posixGroup)(memberUid=$_UID))"`
this line : `echo "DEBUG: _ENTRY [$_ENTRY] _ENTRIES [$_ENTRIES]"`

and just before this line : 
echo_log "Deleting user from secondary group: $_ENTRY"
this line : `echo "DEBUG: _ENTRY [$_ENTRY] _ENTRIES [$_ENTRIES]"`

then : 

**ldapdeleteuser toto**
```
DEBUG: _ENTRY [uid=toto,ou=Users,ou=Samba,dc=annuaire,dc=fr] _ENTRIES []
DEBUG: _ENTRY [] _ENTRIES []
Deleting user from secondary group: 
Successfully deleted user uid=toto,ou=Users,ou=Samba,dc=annuaire,dc=fr from LDAP


```

**Comment by plegrand1** [comment]
In my version i've got this line : 
`echo "$_ENTRIES" | \`

and not this line : 
`[ -n "$_ENTRIES" ] && echo "$_ENTRIES" | \`

Could it be the problem ? no test if $_ENTRIES is empty or not

**Comment by martymac** [comment]
Yes, you must be missing this commit :
https://github.com/martymac/ldapscripts/commit/dbb9fa741215b9ecd4f2f06fba442c98694253e0

It has been fixed in 2.8.0, can you try that version and see if the problem persists ?

**Comment by plegrand1** [comment]
for the moment, as it's a debian package i'm going to test with the good line
I tell you

**Comment by plegrand1** [comment]
**YESSSS**
That was the problem

Do i have to make a report bug ?

**Comment by martymac** [comment]
Thanks but as you can see, it's already fixed upstream.

Maybe you can ask the Debian package maintainer to update to 2.8.0 ?

**Comment by plegrand1** [comment]
I send him a mail to ask if he could update.

**Comment by martymac** [comment]
Great, so I can close that issue.

Thanks for using ldapscripts :)
