### ISSUE TITLE
Allow ldapsetpasswd to set machine account passwords

### ISSUE THREAD

**Issue by andrewgdotcom** [martymac/ldapscripts#12]
It would be nice if ldapsetpasswd searched under `$SUFFIX` instead of `$USUFFIX,$SUFFIX` on line 33, so that it could modify machine accounts as well as users.

**Comment by martymac** [comment]
Hi Andrew,

Good idea, thanks. Maybe by adding a -u/-m switch ? I'll see what I can do here.

Regards,

Ganael.

**Comment by andrewgdotcom** [comment]
Is it possible to create a machine with the same name as a user? If not, there's no need to specify which we're referring to...

**Comment by martymac** [comment]
Hi Andrew,

> Is it possible to create a machine with the same name as a user?

Yes, as accounts are often stored in different branches.

The following commit: https://github.com/martymac/ldapscripts/commit/b1eed4bcd6f2958b746b83ab09a9a15b32e5a847 adds -u and -m options to restrict password change to user and machine branches. You can omit those switches if you want to act on the first matching account found.

Best regards,

Ganael.
