### ISSUE TITLE
Support for multiple configuration files?

### ISSUE THREAD

**Issue by jvalleroy** [martymac/ldapscripts#6]
Would it be possible for ldapscripts to support multiple configuration files? For example, by allowing an alternate config file to be specified as a command line argument or environment variable.

**Comment by martymac** [comment]
Hi James,

It should be quite easy to handle that through an env variable and fallback to the default config file if needed. What's the need ? Handling several directories at once ?

**Comment by SunilMohanAdapa** [comment]
On 10/14/2016 04:00 PM, Ganael Laplanche wrote:

> Hi James,
> 
> It should be quite easy to handle that through an env variable and
> fallback to the default config file if needed. What's the need ?
> Handling several directories at once ?

The FreedomBox web interface (Plinth) is using ldapscripts to manage
user accounts.  So, during setup, Plinth updates the configuration file
as needed.  If the setup happens from within the Plinth package, it
violates the Debian policy for modifying the configuration file of
another package directly.  While this situation can handled by
implementing configuration mechanism in the ldapscripts Debian package,
it seemed more appropriate that plinth provides its own additional
configuration file which it alone uses leaving the main configuration to
the system administrator for other needs.

## 

Sunil

**Comment by martymac** [comment]
OK, good idea, thanks :) I'll try to provide a patch ASAP.

Regards,
Ganael.

**Comment by martymac** [comment]
Can you try the attached patch and tell me if it fits your needs ? Just define the LDAPSCRIPTS_CONF environment variable to override the default configuration file when calling a script.
[runtime.diff.txt](https://github.com/martymac/ldapscripts/files/534441/runtime.diff.txt)

**Comment by jvalleroy** [comment]
@martymac I have tested this script using an alternate config file defined in LDAPSCRIPTS_CONF. Seems to be working ok.

**Comment by martymac** [comment]
Committed into rev. c20600b, thanks!
