### ISSUE TITLE
ldaprenameuser doesn't clean up group memberships

### ISSUE THREAD

**Issue by pwalz** [martymac/ldapscripts#7]
When using `ldaprenameuser`, it doesn't take care of any groups the account is in. For example, if `john` is a member of the `staff` group, and the account is renamed to `johnsmith`, the `staff` group will still have `john` as a member and not `johnsmith`. I don't know if this is an intentional omission (maybe due to some LDAP implementations automatically fixing the problem) - if it wasn't intentional, would you take a pull request to fix it?

**Comment by martymac** [comment]
Hi,

Sure, this could be interesting. This is the same kind of operation as :

https://github.com/martymac/ldapscripts/commit/9806d8cb9e1bbc14fbce631457a325317be99ffe

Maybe that diff can serve as an inspiration ?

Regards,

Ganael.

**Comment by pwalz** [comment]
Good inspiration, for sure - seeing that code is what made me think that `ldaprenameuser` should update group memberships. I've submitted PR #8 as a possible solution.
